// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: db.query.sql

package database

import (
	"context"
	"database/sql"
)

const createAssignment = `-- name: CreateAssignment :execresult
insert into assignments (user_id, object_ref, object_id, role_id, description) 
       values (?, ?, ?, ?, ?)
`

type CreateAssignmentParams struct {
	UserID      int64
	ObjectRef   sql.NullString
	ObjectID    sql.NullInt64
	RoleID      sql.NullInt32
	Description sql.NullString
}

func (q *Queries) CreateAssignment(ctx context.Context, arg CreateAssignmentParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, createAssignment,
		arg.UserID,
		arg.ObjectRef,
		arg.ObjectID,
		arg.RoleID,
		arg.Description,
	)
}

const createNote = `-- name: CreateNote :execresult
insert into notes (object_ref, object_id, content, user_id) 
       values (?, ?, ?, ?)
`

type CreateNoteParams struct {
	ObjectRef sql.NullString
	ObjectID  sql.NullInt64
	Content   sql.NullString
	UserID    sql.NullInt64
}

func (q *Queries) CreateNote(ctx context.Context, arg CreateNoteParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, createNote,
		arg.ObjectRef,
		arg.ObjectID,
		arg.Content,
		arg.UserID,
	)
}

const createProject = `-- name: CreateProject :execresult
insert into projects (title, description, start_date, end_date, status) 
       values (?, ?, ?, ?, ?)
`

type CreateProjectParams struct {
	Title       string
	Description sql.NullString
	StartDate   sql.NullTime
	EndDate     sql.NullTime
	Status      int8
}

func (q *Queries) CreateProject(ctx context.Context, arg CreateProjectParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, createProject,
		arg.Title,
		arg.Description,
		arg.StartDate,
		arg.EndDate,
		arg.Status,
	)
}

const createRole = `-- name: CreateRole :execresult
insert into roles (name, description) 
       values (?, ?)
`

type CreateRoleParams struct {
	Name        string
	Description sql.NullString
}

func (q *Queries) CreateRole(ctx context.Context, arg CreateRoleParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, createRole, arg.Name, arg.Description)
}

const createStatus = `-- name: CreateStatus :execresult
insert into statuses (name, description) 
       values (?, ?)
`

type CreateStatusParams struct {
	Name        string
	Description sql.NullString
}

func (q *Queries) CreateStatus(ctx context.Context, arg CreateStatusParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, createStatus, arg.Name, arg.Description)
}

const createTask = `-- name: CreateTask :execresult
insert into tasks (title, description, start_date, end_date, status, project_id) 
       values (?, ?, ?, ?, ?, ?)
`

type CreateTaskParams struct {
	Title       string
	Description sql.NullString
	StartDate   sql.NullTime
	EndDate     sql.NullTime
	Status      int8
	ProjectID   sql.NullInt64
}

func (q *Queries) CreateTask(ctx context.Context, arg CreateTaskParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, createTask,
		arg.Title,
		arg.Description,
		arg.StartDate,
		arg.EndDate,
		arg.Status,
		arg.ProjectID,
	)
}

const createUser = `-- name: CreateUser :execresult
insert into users (name, username, password, phone) 
       values  ( ?, ?, ?, ? )
`

type CreateUserParams struct {
	Name     string
	Username string
	Password string
	Phone    sql.NullString
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, createUser,
		arg.Name,
		arg.Username,
		arg.Password,
		arg.Phone,
	)
}

const deleteAssignment = `-- name: DeleteAssignment :exec
delete from assignments where id = ?
`

func (q *Queries) DeleteAssignment(ctx context.Context, id int32) error {
	_, err := q.db.ExecContext(ctx, deleteAssignment, id)
	return err
}

const deleteNote = `-- name: DeleteNote :exec
delete from notes where id = ?
`

func (q *Queries) DeleteNote(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteNote, id)
	return err
}

const deleteProject = `-- name: DeleteProject :exec
delete from projects where id = ?
`

func (q *Queries) DeleteProject(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteProject, id)
	return err
}

const deleteRole = `-- name: DeleteRole :exec
delete from roles where id = ?
`

func (q *Queries) DeleteRole(ctx context.Context, id int32) error {
	_, err := q.db.ExecContext(ctx, deleteRole, id)
	return err
}

const deleteStatus = `-- name: DeleteStatus :exec
delete from statuses where id = ?
`

func (q *Queries) DeleteStatus(ctx context.Context, id int32) error {
	_, err := q.db.ExecContext(ctx, deleteStatus, id)
	return err
}

const deleteTask = `-- name: DeleteTask :exec
delete from tasks where id = ?
`

func (q *Queries) DeleteTask(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteTask, id)
	return err
}

const deleteUser = `-- name: DeleteUser :exec
delete from users where id = ?
`

func (q *Queries) DeleteUser(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteUser, id)
	return err
}

const findProject = `-- name: FindProject :one
select id, title, description, user_id, start_date, end_date, status from projects where id = ? limit 1
`

func (q *Queries) FindProject(ctx context.Context, id int64) (Project, error) {
	row := q.db.QueryRowContext(ctx, findProject, id)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Description,
		&i.UserID,
		&i.StartDate,
		&i.EndDate,
		&i.Status,
	)
	return i, err
}

const findUser = `-- name: FindUser :one
select id, name, username, password, phone, status from users where id = ? limit 1
`

func (q *Queries) FindUser(ctx context.Context, id int64) (User, error) {
	row := q.db.QueryRowContext(ctx, findUser, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Username,
		&i.Password,
		&i.Phone,
		&i.Status,
	)
	return i, err
}

const getProject = `-- name: GetProject :many
select id, title, description, user_id, start_date, end_date, status from projects
`

func (q *Queries) GetProject(ctx context.Context) ([]Project, error) {
	rows, err := q.db.QueryContext(ctx, getProject)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Project
	for rows.Next() {
		var i Project
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Description,
			&i.UserID,
			&i.StartDate,
			&i.EndDate,
			&i.Status,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getProjectsPaginated = `-- name: GetProjectsPaginated :many
SELECT id, title, description, user_id, start_date, end_date, status FROM projects
WHERE 
    (? IS NULL OR title LIKE ? OR description LIKE ?)
    AND (? IS NULL OR status = ?)
ORDER BY id DESC
LIMIT ? OFFSET ?
`

type GetProjectsPaginatedParams struct {
	Search sql.NullString
	Status sql.NullInt16
	Limit  int32
	Offset int32
}

func (q *Queries) GetProjectsPaginated(ctx context.Context, arg GetProjectsPaginatedParams) ([]Project, error) {
	rows, err := q.db.QueryContext(ctx, getProjectsPaginated,
		arg.Search,
		arg.Search,
		arg.Search,
		arg.Status,
		arg.Status,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Project
	for rows.Next() {
		var i Project
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Description,
			&i.UserID,
			&i.StartDate,
			&i.EndDate,
			&i.Status,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const toggleUser = `-- name: ToggleUser :exec
update users set status =  1 - status where id = ?
`

func (q *Queries) ToggleUser(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, toggleUser, id)
	return err
}

const updateAssignment = `-- name: UpdateAssignment :execresult
update assignments set user_id = ?, object_ref = ?, object_id = ?, role_id = ?, description = ? 
       where id = ?
`

type UpdateAssignmentParams struct {
	UserID      int64
	ObjectRef   sql.NullString
	ObjectID    sql.NullInt64
	RoleID      sql.NullInt32
	Description sql.NullString
	ID          int32
}

func (q *Queries) UpdateAssignment(ctx context.Context, arg UpdateAssignmentParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, updateAssignment,
		arg.UserID,
		arg.ObjectRef,
		arg.ObjectID,
		arg.RoleID,
		arg.Description,
		arg.ID,
	)
}

const updateNote = `-- name: UpdateNote :execresult
update notes set object_ref = ?, object_id = ?, content = ?, user_id = ?
       where id = ?
`

type UpdateNoteParams struct {
	ObjectRef sql.NullString
	ObjectID  sql.NullInt64
	Content   sql.NullString
	UserID    sql.NullInt64
	ID        int64
}

func (q *Queries) UpdateNote(ctx context.Context, arg UpdateNoteParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, updateNote,
		arg.ObjectRef,
		arg.ObjectID,
		arg.Content,
		arg.UserID,
		arg.ID,
	)
}

const updateProject = `-- name: UpdateProject :execresult
update projects set title = ?, description = ?, start_date = ?, end_date = ?, status = ? 
       where id = ?
`

type UpdateProjectParams struct {
	Title       string
	Description sql.NullString
	StartDate   sql.NullTime
	EndDate     sql.NullTime
	Status      int8
	ID          int64
}

func (q *Queries) UpdateProject(ctx context.Context, arg UpdateProjectParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, updateProject,
		arg.Title,
		arg.Description,
		arg.StartDate,
		arg.EndDate,
		arg.Status,
		arg.ID,
	)
}

const updateRole = `-- name: UpdateRole :execresult
update roles set name = ?, description = ? where id = ?
`

type UpdateRoleParams struct {
	Name        string
	Description sql.NullString
	ID          int32
}

func (q *Queries) UpdateRole(ctx context.Context, arg UpdateRoleParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, updateRole, arg.Name, arg.Description, arg.ID)
}

const updateStatus = `-- name: UpdateStatus :execresult
update statuses set name = ?, description = ? where id = ?
`

type UpdateStatusParams struct {
	Name        string
	Description sql.NullString
	ID          int32
}

func (q *Queries) UpdateStatus(ctx context.Context, arg UpdateStatusParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, updateStatus, arg.Name, arg.Description, arg.ID)
}

const updateTask = `-- name: UpdateTask :execresult
update tasks set title = ?, description = ?, start_date = ?, end_date = ?, status = ? 
       where id = ?
`

type UpdateTaskParams struct {
	Title       string
	Description sql.NullString
	StartDate   sql.NullTime
	EndDate     sql.NullTime
	Status      int8
	ID          int64
}

func (q *Queries) UpdateTask(ctx context.Context, arg UpdateTaskParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, updateTask,
		arg.Title,
		arg.Description,
		arg.StartDate,
		arg.EndDate,
		arg.Status,
		arg.ID,
	)
}
