// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package database

import (
	"database/sql"
)

type Assignment struct {
	ID     int32
	UserID int64
	// either projects or tasks
	ObjectRef sql.NullString
	// primary id of projects or tasks
	ObjectID    sql.NullInt64
	RoleID      sql.NullInt32
	Description sql.NullString
}

type Note struct {
	ID int64
	// either projects or tasks
	ObjectRef sql.NullString
	// primary id of projects or tasks
	ObjectID  sql.NullInt64
	Content   sql.NullString
	UserID    sql.NullInt64
	CreatedAt sql.NullTime
	UpdatedAt sql.NullTime
}

type Project struct {
	ID          int64
	Title       string
	Description sql.NullString
	UserID      sql.NullInt64
	StartDate   sql.NullTime
	EndDate     sql.NullTime
	Status      int8
}

type Role struct {
	ID          int32
	Name        string
	Description sql.NullString
}

type Status struct {
	ID          int32
	Name        string
	Description sql.NullString
}

type Task struct {
	ID          int64
	ProjectID   sql.NullInt64
	Title       string
	Description sql.NullString
	UserID      sql.NullInt64
	StartDate   sql.NullTime
	EndDate     sql.NullTime
	Status      int8
}

type User struct {
	ID       int64
	Name     string
	Username string
	Password string
	Phone    sql.NullString
	Status   sql.NullInt16
}
